# Generated by Django 5.2.16 on 2026-07-19 22:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('receive_email', models.BooleanField(default=True, verbose_name='دریافت پست الکترونیکی (Email)')),
                ('receive_sms', models.BooleanField(default=True, verbose_name='دریافت پیامک متنی (SMS)')),
                ('receive_marketing', models.BooleanField(default=True, verbose_name='دریافت پیام\u200cهای بازاریابی')),
                ('receive_system_alerts', models.BooleanField(default=True, verbose_name='دریافت هشدارهای سیستمی فوری')),
                ('receive_promotions', models.BooleanField(default=True, verbose_name='دریافت کمپین\u200cها و تخفیف\u200cها')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات دریافت اعلان',
                'verbose_name_plural': '۳. تنظیمات دریافت اعلانات کاربران',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(help_text='مثال: welcome_email', max_length=100, unique=True, verbose_name='شناسه الگو (انگلیسی)')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فارسی الگو')),
                ('channel', models.CharField(choices=[('email', 'پست الکترونیکی (Email)'), ('sms', 'پیامک متنی (SMS)'), ('in_app', 'اعلان درون\u200cبرنامه\u200cای (In-App)')], max_length=20, verbose_name='کانال ارسال')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='موضوع ایمیل')),
                ('body', models.TextField(help_text='پشتیبانی از متغیرهایی مثل {{customer_name}} و {{tracking_code}}', verbose_name='متن الگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'الگوی اعلان',
                'verbose_name_plural': '۱. الگوهای اعلانات و پیام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20, verbose_name='کانال')),
                ('recipient', models.CharField(help_text='شماره همراه یا ایمیل', max_length=255, verbose_name='آدرس گیرنده')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='موضوع اعلان')),
                ('body', models.TextField(verbose_name='متن نهایی پیام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار ارسال (Pending)'), ('processing', 'در حال پردازش (Processing)'), ('sent', 'با موفقیت ارسال شد (Sent)'), ('failed', 'ناموفق / خطا (Failed)'), ('retry', 'تلاش مجدد (Retry)')], default='pending', max_length=20, verbose_name='وضعیت ارسال')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای مجدد')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='حداکثر دفعات تلاش مجدد')),
                ('error_log', models.TextField(blank=True, verbose_name='لاگ خطای ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟ (مخصوص In-App)')),
                ('is_archived', models.BooleanField(default=False, verbose_name='بایگانی شده؟')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال موفق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گیرنده')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate', verbose_name='الگوی پیام')),
            ],
            options={
                'verbose_name': 'اعلان صف ارسال',
                'verbose_name_plural': '۲. صف اعلانات و پیام\u200cها (Queue)',
                'ordering': ['-created_at'],
            },
        ),
    ]
