# Generated by Django 5.2.16 on 2026-07-17 21:08

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('org', models.CharField(max_length=150, verbose_name='نام سازمان / شرکت')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تماس'), ('called', 'تماس گرفته شد'), ('failed', 'ناموفق / عدم پاسخگویی')], default='pending', max_length=20, verbose_name='وضعیت بررسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت درخواست')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره سازمانی',
                'verbose_name_plural': '۴. درخواست\u200cهای مشاوره همکاران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.CharField(help_text='مانند: matte', max_length=50, primary_key=True, serialize=False, verbose_name='شناسه یکتا (انگلیسی)')),
                ('label', models.CharField(max_length=100, verbose_name='نام خدمت تکمیلی')),
                ('factor', models.FloatField(help_text='مثلا 0.12 برای افزایش 12 درصدی قیمت', verbose_name='ضریب قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
            ],
            options={
                'verbose_name': 'خدمت تکمیلی',
                'verbose_name_plural': '۲. خدمات تکمیلی چاپی',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='مثال: branding-cafe-sin', max_length=100, unique=True, verbose_name='آدرس متنی یکتا (slug انگلیسی)')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان نمونه کار')),
                ('client', models.CharField(max_length=100, verbose_name='نام مشتری / برند')),
                ('category', models.CharField(help_text='مثال: کارت ویزیت و هویت بصری', max_length=100, verbose_name='دسته\u200cبندی نمونه کار')),
                ('description', models.TextField(verbose_name='توضیحات و داستان پروژه')),
                ('cover_image', models.ImageField(upload_to='portfolio/covers/', verbose_name='تصویر اصلی پروژه')),
                ('testimonial_text', models.TextField(blank=True, verbose_name='متن نقل\u200cقول / رضایت مشتری')),
                ('testimonial_author', models.CharField(blank=True, max_length=100, verbose_name='نویسنده نقل\u200cقول')),
                ('testimonial_role', models.CharField(blank=True, max_length=100, verbose_name='سمت نویسنده')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': '۵. گالری نمونه کارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text='مانند: business-card', max_length=50, primary_key=True, serialize=False, verbose_name='شناسه یکتا (انگلیسی)')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان محصول')),
                ('category', models.CharField(choices=[('stationary', 'اوراق اداری و کارت ویزیت'), ('advertising', 'تبلیغات و نمایشگاهی'), ('packaging', 'بسته\u200cبندی و جعبه'), ('label', 'لیبل و استیکر'), ('other', 'سایر موارد اختصاصی')], default='stationary', max_length=30, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('unit_price', models.IntegerField(verbose_name='قیمت واحد (تومان)')),
                ('delivery_days', models.PositiveIntegerField(default=5, verbose_name='زمان تقریبی تحویل (روز)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
            ],
            options={
                'verbose_name': 'محصول و تعرفه',
                'verbose_name_plural': '۱. محصولات و تعرفه\u200cها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/galleries/', verbose_name='تصویر گالری')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='orders.portfolioproject', verbose_name='پروژه مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری نمونه کارها',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد رهگیری')),
                ('quantity', models.PositiveIntegerField(verbose_name='تیراژ (تعداد)')),
                ('material', models.CharField(max_length=100, verbose_name='جنس کاغذ/مقوا')),
                ('size', models.CharField(max_length=100, verbose_name='ابعاد')),
                ('print_side', models.CharField(max_length=100, verbose_name='نوع چاپ (یک\u200cرو / دورو)')),
                ('file', models.FileField(blank=True, null=True, upload_to=orders.models.order_file_upload_path, verbose_name='فایل طراحی')),
                ('file_name_display', models.CharField(blank=True, max_length=255, verbose_name='نام فایل ارسالی')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='شماره موبایل مشتری')),
                ('customer_note', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
                ('shipping_city', models.CharField(blank=True, max_length=50, verbose_name='شهر مقصد')),
                ('shipping_address', models.TextField(blank=True, verbose_name='آدرس دقیق پستی')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی ۱۰ رقمی')),
                ('estimated_price', models.IntegerField(verbose_name='مبلغ برآورد شده (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی فایل'), ('processing', 'در حال طراحی / آماده\u200cسازی'), ('printing', 'در حال چاپ در چاپخانه'), ('ready', 'آماده تحویل / بسته\u200cبندی شده'), ('shipped', 'تحویل پست / ارسال شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت فرآیند سفارش')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده و موفق'), ('failed', 'پرداخت ناموفق'), ('refunded', 'مرجوع شده (سفارش لغو شده)')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین بانکی (درگاه مستقیم)'), ('card_transfer', 'کارت به کارت (تایید ادمین)'), ('manual', 'تسویه حساب حضوری / اعتباری')], default='online', max_length=20, verbose_name='درگاه پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری بانکی (RefID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('finishes', models.ManyToManyField(blank=True, to='orders.finish', verbose_name='خدمات تکمیلی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'سفارش مشتری',
                'verbose_name_plural': '۳. سفارشات ثبت شده چاپی',
                'ordering': ['-created_at'],
            },
        ),
    ]
