# Generated by Django 5.2.16 on 2026-07-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='تنظیمات پیش\u200cفرض چاپخانه', max_length=100, verbose_name='عنوان پیکربندی')),
                ('double_side_factor', models.FloatField(default=1.16, help_text='پیش\u200cفرض ۱.۱۶ معادل افزایش ۱۶ درصدی قیمت', verbose_name='ضریب چاپ دورو رنگی')),
                ('rounding_threshold', models.IntegerField(default=10000, help_text='پیش\u200cفرض ۱۰۰۰۰ برای رند کردن به نزدیکترین ده هزار تومان', verbose_name='مبنای رند کردن قیمت (تومان)')),
                ('vat_percentage', models.PositiveIntegerField(default=0, help_text='مثلا 10 برای اعمال مالیات ۱۰ درصدی', verbose_name='درصد مالیات بر ارزش افزوده (VAT)')),
                ('base_shipping_cost', models.IntegerField(default=50000, verbose_name='هزینه ثابت حمل و نقل (تومان)')),
                ('free_shipping_threshold', models.IntegerField(default=3000000, help_text='سفارشات بالاتر از این مبلغ هزینه ارسال صفر خواهند داشت', verbose_name='حداقل مبلغ سفارش برای ارسال رایگان (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟ (فقط یک پیکربندی فعال است)')),
            ],
            options={
                'verbose_name': 'تنظیمات عمومی فرمول و ارسال',
                'verbose_name_plural': ' تنظیمات عمومی فرمول و حمل و نقل',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه حمل و نقل (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_payable',
            field=models.IntegerField(default=0, verbose_name='مبلغ نهایی قابل پرداخت (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.IntegerField(verbose_name='مبلغ برآورد شده تولید (تومان)'),
        ),
    ]
