# Generated by Django 5.2.16 on 2026-07-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_globalconfiguration_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_profit',
            field=models.IntegerField(default=0, verbose_name='سود خالص سفارش (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_cost',
            field=models.IntegerField(default=0, verbose_name='کل هزینه خام تولید (تومان)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_production_cost',
            field=models.IntegerField(default=1500, help_text='هزینه کاغذ، مرکب و ملزومات برای محاسبه سود خالص حسابداری', verbose_name='هزینه خام تولید هر واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(verbose_name='قیمت فروش پایه هر واحد (تومان)'),
        ),
    ]
