# Generated by Django 5.2.16 on 2026-07-18 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_net_profit_order_production_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فرم عمومی')),
                ('material', models.CharField(help_text='مثال: گلاسه ۳۰۰ گرم لمینت کارت ویزیت', max_length=100, verbose_name='جنس مشترک فرم')),
                ('max_capacity', models.PositiveIntegerField(default=80, help_text='مثلا ۸۰ کارت ویزیت در یک شیت', verbose_name='حداکثر ظرفیت فرم (تعداد کارت)')),
                ('status', models.CharField(choices=[('collecting', 'در حال جمع\u200cآوری کارت\u200cها (باز)'), ('full', 'تکمیل شده - در انتظار ارسال به لیتوگرافی'), ('printing', 'در حال چاپ در چاپخانه'), ('finished', 'برش\u200cخورده و پایان\u200cیافته')], default='collecting', max_length=20, verbose_name='وضعیت فرم چاپی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فرم')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته\u200cشدن و تکمیل فرم')),
            ],
            options={
                'verbose_name': 'فرم عمومی چاپی',
                'verbose_name_plural': '۷. شیت\u200cها و فرم\u200cهای عمومی چاپخانه',
            },
        ),
        migrations.CreateModel(
            name='SMSNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره دریافت\u200cکننده')),
                ('message_text', models.TextField(verbose_name='متن پیامک ارسال شده')),
                ('status', models.CharField(default='sent', max_length=20, verbose_name='وضعیت دلیوری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'لاگ پیامک ارسال شده',
                'verbose_name_plural': '۸. لاگ\u200cهای اطلاع\u200cرسانی پیامکی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام پیمانکار / کارگاه')),
                ('specialty', models.CharField(help_text='مثال: لیتوگرافی، چاپ افست، سلفون\u200cکشی', max_length=100, verbose_name='تخصص اصلی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس کارگاه')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='امتیاز کیفیت کار (از ۵)')),
            ],
            options={
                'verbose_name': 'پیمانکار همکار',
                'verbose_name_plural': '۶. پیمانکاران و کارگاه\u200cهای همکار',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_sample_pack',
            field=models.BooleanField(default=False, verbose_name='درخواست پک نمونه رایگان؟'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه فاکتور پیمانکار (تومان)'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام رسمی شرکت / سازمان')),
                ('registration_number', models.CharField(max_length=50, verbose_name='شماره ثبت')),
                ('tax_id', models.CharField(max_length=50, verbose_name='شناسه ملی حقوقی')),
                ('economic_code', models.CharField(blank=True, max_length=50, verbose_name='کد اقتصادی')),
                ('company_address', models.TextField(verbose_name='آدرس قانونی شرکت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر رابط حقوقی')),
            ],
            options={
                'verbose_name': 'پروفایل حقوقی شرکت',
                'verbose_name_plural': '۱۱. پروفایل مشتریان حقوقی و سازمان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: دفتر مرکزی تهران', max_length=100, verbose_name='عنوان آدرس')),
                ('address_type', models.CharField(choices=[('home', 'خانه (منزل)'), ('office', 'دفتر کار / شرکت'), ('warehouse', 'انبار تخلیه بار')], default='office', max_length=20, verbose_name='نوع آدرس')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس دقیق پستی')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی ۱۰ رقمی')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض ارسال؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس مشتری',
                'verbose_name_plural': '۱۰. دفترچه آدرس\u200cهای مشتریان',
            },
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='شناسه محصول')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='آخرین مرحله ویزارد')),
                ('specs_json', models.JSONField(verbose_name='تنظیمات ذخیره شده به فرمت JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین زمان ذخیره\u200cسازی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیش\u200cنویس سفارش',
                'verbose_name_plural': '۹. سفارش\u200cهای پیش\u200cنویس (Drafts)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='متن پیام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chats/images/', verbose_name='تصویر ارسالی')),
                ('file', models.FileField(blank=True, null=True, upload_to='chats/files/', verbose_name='فایل ضمیمه')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='orders.order', verbose_name='سفارش مربوطه')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام سفارش چت',
                'verbose_name_plural': '۱۳. گفتگوهای زنده کارگاه و مشتری',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='printing_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.printingsheet', verbose_name='شیت چاپی مربوطه'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='orders.supplier', verbose_name='کارگاه برون\u200cسپاری شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.supplier', verbose_name='پیمانکار پیش\u200cفرض'),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع تیکت')),
                ('department', models.CharField(choices=[('sales', 'واحد فروش و سفارشات'), ('design', 'آتلیه طراحی و بررسی فایل'), ('printing', 'کارگاه چاپ و صحافی'), ('finance', 'حسابداری و مالی')], default='sales', max_length=20, verbose_name='دپارتمان')),
                ('priority', models.CharField(choices=[('low', 'کم / عمومی'), ('medium', 'متوسط / فنی'), ('high', 'فوری / مالی چاپی')], default='medium', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('open', 'جدید / باز'), ('answered', 'پاسخ داده شده'), ('customer_reply', 'پاسخ مشتری'), ('closed', 'بسته شده / خاتمه یافته')], default='open', max_length=20, verbose_name='وضعیت تیکت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': '۱۲. تیکت\u200cهای پشتیبانی مشتریان',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پاسخ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='orders.supportticket', verbose_name='تیکت مربوطه')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت\u200cهای پشتیبانی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'سفارشات و فرآیند چاپ'), ('payment', 'تراکنش\u200cهای مالی و درگاه'), ('message', 'پیام جدید آتلیه'), ('system', 'پیام\u200cهای سیستمی عمومی'), ('academy', 'آکادمی و دوره\u200cهای جدید'), ('blog', 'وبلاگ و مطالب جدید')], default='order', max_length=20, verbose_name='نوع اعلان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اعلان')),
                ('description', models.TextField(verbose_name='توضیحات اعلان')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name='آدرس کلیک و ارجاع')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان کاربر',
                'verbose_name_plural': '۱۴. اعلان\u200cهای سیستم پنل کاربری',
                'ordering': ['-created_at'],
            },
        ),
    ]
