# Generated by Django 5.2.16 on 2026-07-18 16:31

import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_printingsheet_smsnotificationlog_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_supplier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='estimated_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='file_name_display',
        ),
        migrations.RemoveField(
            model_name='order',
            name='finishes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_sample_pack',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='net_profit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='print_side',
        ),
        migrations.RemoveField(
            model_name='order',
            name='printing_sheet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='production_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_cost',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده و موفق'), ('failed', 'پرداخت ناموفق'), ('refunded', 'مرجوع شده (سفارش لغو شده)')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت فاکتور'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_payable',
            field=models.IntegerField(default=0, verbose_name='کل مبلغ نهایی فاکتور (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد رهگیری فاکتور'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('quantity', models.PositiveIntegerField(verbose_name='تیراژ (تعداد)')),
                ('material', models.CharField(max_length=100, verbose_name='جنس کاغذ/مقوا')),
                ('size', models.CharField(max_length=100, verbose_name='ابعاد')),
                ('print_side', models.CharField(max_length=100, verbose_name='نوع چاپ (یک\u200cرو / دورو)')),
                ('file', models.FileField(blank=True, null=True, upload_to=orders.models.job_file_upload_path, verbose_name='فایل طراحی اختصاصی')),
                ('file_name_display', models.CharField(blank=True, max_length=255, verbose_name='نام فایل ارسالی')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام کار روی شیت')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='شماره تماس پیگیری')),
                ('customer_note', models.TextField(blank=True, verbose_name='توضیحات فنی کارگاه')),
                ('estimated_price', models.IntegerField(verbose_name='مبلغ فروش این کار (تومان)')),
                ('production_cost', models.IntegerField(default=0, verbose_name='کل هزینه خام تولید این کار (تومان)')),
                ('net_profit', models.IntegerField(default=0, verbose_name='سود خالص این کار (تومان)')),
                ('is_sample_pack', models.BooleanField(default=False, verbose_name='درخواست پک نمونه رایگان؟')),
                ('supplier_cost', models.IntegerField(default=0, verbose_name='هزینه فاکتور پیمانکار (تومان)')),
                ('status', models.CharField(choices=[('created', 'ثبت شده / آماده بررسی فایل'), ('review', 'در حال بررسی فنی فایل توسط ناظر'), ('design', 'در حال طراحی / اصلاحات رنگ آتلیه'), ('printing', 'در حال تولید در چاپخانه فیزیکی'), ('packaging', 'بسته\u200cبندی و کنترل کیفیت'), ('shipping', 'تحویل پست / ارسال شده'), ('delivered', 'تحویل شده به مشتری'), ('cancelled', 'لغو شده')], default='created', max_length=20, verbose_name='وضعیت تولید فیزیکی این کار')),
                ('assigned_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL, verbose_name='طراح ناظر فایل')),
                ('assigned_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='orders.supplier', verbose_name='کارگاه پیمانکار همکار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('finishes', models.ManyToManyField(blank=True, to='orders.finish', verbose_name='خدمات تکمیلی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='orders.order', verbose_name='سفارش فاکتور مالی')),
                ('printing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orders.printingsheet', verbose_name='شیت چاپی مربوطه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='orders.product', verbose_name='محصول')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'کار تولیدی (Job)',
                'verbose_name_plural': ' کارهای تولیدی کارگاه (Jobs)',
                'ordering': ['id'],
            },
        ),
    ]
