# Generated by Django 5.2.16 on 2026-07-19 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_assigned_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer_note',
            field=models.TextField(blank=True, verbose_name='توضیحات سفارش'),
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(max_length=150, verbose_name='نام مخاطب')),
                ('position', models.CharField(help_text='مثال: مدیر مالی، طراح، کارپرداز', max_length=100, verbose_name='سمت / دپارتمان')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل مستقیم')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='orders.companyprofile', verbose_name='شرکت مربوطه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'مخاطب شرکت همکار',
                'verbose_name_plural': 'کارمندان و مخاطبین شرکت\u200cهای حقوقی',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('customer_code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='کد مشتری انحصاری')),
                ('is_vip', models.BooleanField(default=False, verbose_name='آیا مشتری VIP است؟')),
                ('score', models.PositiveIntegerField(default=100, help_text='محاسبه هوشمند بر اساس وفاداری و تسویه\u200cحساب\u200cها', verbose_name='امتیاز اعتباری مشتری (از ۱۰۰)')),
                ('credit_limit', models.IntegerField(default=0, verbose_name='سقف اعتبار تجاری (تومان)')),
                ('credit_settlement_days', models.PositiveIntegerField(default=30, verbose_name='مهلت تسویه حساب (روز)')),
                ('health_status', models.CharField(choices=[('healthy', 'سالم و فعال (Healthy)'), ('risk', 'در خطر از دست رفتن (Risk)'), ('inactive', 'غیرفعال (Inactive)'), ('lost', 'از دست رفته (Lost)')], default='healthy', max_length=20, verbose_name='وضعیت سلامت مشتری')),
                ('internal_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای مخفی سرپرست فروش')),
                ('tags', models.CharField(default='Loyal', help_text='مثال: VIP, Gold, Wholesale, Agency', max_length=255, verbose_name='تگ\u200cهای مشتری')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='امتیاز باشگاه مشتریان')),
                ('loyalty_level', models.CharField(default='برنزی', max_length=50, verbose_name='سطح وفاداری')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل مشتری CRM',
                'verbose_name_plural': '۱۵. پرونده ۳۶۰ درجه مشتریان (CRM)',
            },
        ),
    ]
