# Generated by Django 5.2.16 on 2026-07-19 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_job_customer_note_companycontact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='position',
            field=models.CharField(max_length=100, verbose_name='سمت / دپارتمان'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='score',
            field=models.PositiveIntegerField(default=100, verbose_name='امتیاز اعتباری مشتری (از ۱۰۰)'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='tags',
            field=models.CharField(default='Loyal', max_length=255, verbose_name='تگ\u200cهای مشتری'),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سفارش'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد تخفیف اختصاصی')),
                ('is_percentage', models.BooleanField(default=True, help_text='در غیر این صورت تخفیف نقدی اعمال می\u200cشود', verbose_name='تخفیف درصدی؟')),
                ('discount_amount', models.IntegerField(verbose_name='میزان تخفیف (درصد یا تومان)')),
                ('minimum_amount', models.IntegerField(default=0, verbose_name='حداقل خرید فعال\u200cسازی (تومان)')),
                ('max_discount', models.IntegerField(default=1000000, verbose_name='حداکثر سقف تخفیف نقدی (تومان)')),
                ('expiration_date', models.DateTimeField(verbose_name='تاریخ انقضا کوپن')),
                ('max_usages', models.PositiveIntegerField(default=100, verbose_name='حداکثر دفعات مصرف کل')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات مصرف شده فعلی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': '۱۸. کدهای تخفیف و کوپن\u200cها (Coupons)',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('expense_type', models.CharField(choices=[('paper', 'هزینه کاغذ و مقوا چاپی'), ('ink', 'هزینه مرکب، زینک و جوهر افست'), ('packaging', 'ملزومات بسته\u200cبندی (کارتن، چسب)'), ('shipping', 'کرایه حمل و نقل و ارسال پست'), ('salary', 'حقوق و دستمزد پرسنل چاپخانه'), ('electricity', 'قبوض خدماتی (برق کارگاه)'), ('maintenance', 'تعمیر و نگهداری ماشین\u200cآلات چاپی'), ('misc', 'هزینه\u200cهای متفرقه عمومی اداری')], max_length=30, verbose_name='نوع هزینه')),
                ('amount', models.IntegerField(verbose_name='مبلغ هزینه (تومان)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات و بابت هزینه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'هزینه کارگاه',
                'verbose_name_plural': '۱۶. دفتر ثبت هزینه\u200cهای جاری (Expenses)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('amount', models.IntegerField(verbose_name='مبلغ مرجوعی (تومان)')),
                ('reason', models.TextField(verbose_name='دلیل استرداد وجه')),
                ('status', models.CharField(choices=[('requested', 'درخواست شده (معلق)'), ('approved', 'تایید شده (در انتظار تسویه)'), ('rejected', 'رد شده'), ('paid', 'تسویه شده و پرداخت موفق')], default='requested', max_length=20, verbose_name='وضعیت استرداد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='اپراتور ممیزی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order', verbose_name='سفارش فاکتور مالی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'تراکنش مرجوعی',
                'verbose_name_plural': '۱۷. درخواست\u200cهای استرداد وجه (Refunds)',
                'ordering': ['-created_at'],
            },
        ),
    ]
