# Generated by Django 5.2.16 on 2026-07-19 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_companycontact_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان قانون اتوماسیون')),
                ('trigger_event', models.CharField(choices=[('order_created', 'ثبت نهایی سفارش جدید (OrderCreated)'), ('payment_completed', 'تسویه حساب موفق فاکتور (PaymentCompleted)'), ('file_uploaded', 'آپلود فایل جدید طرح مشتری (FileUploaded)'), ('qc_failed', 'رد صلاحیت کیفی کار چاپی (QCFailed)')], max_length=50, verbose_name='رویداد راه\u200cانداز (Trigger)')),
                ('action_type', models.CharField(choices=[('send_sms', 'ارسال پیامک اطلاع\u200cرسانی خودکار'), ('assign_designer', 'انتساب خودکار طراح ناظر آتلیه'), ('notify_finance', 'ارسال هشدار به واحد حسابداری'), ('change_status', 'تغییر خودکار وضعیت تولید کارگاهی')], max_length=50, verbose_name='نوع اکشن اتوماتیک')),
                ('action_payload', models.TextField(blank=True, verbose_name='متن پیامک یا پارامترهای اکشن (Payload)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'قانون اتوماسیون',
                'verbose_name_plural': '۲۰. قوانین موتور اتوماسیون کارگاه (Automation)',
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('status', models.CharField(choices=[('executed', 'با موفقیت اجرا شد (Executed)'), ('failed', 'ناموفق / خطا (Failed)'), ('skipped', 'نادیده\u200cگرفته شده (Skipped)'), ('retry', 'تلاش مجدد (Retry)')], default='executed', max_length=20, verbose_name='وضعیت اجرا')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات و گزارش لاگ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.automationrule', verbose_name='قانون مربوطه')),
            ],
            options={
                'verbose_name': 'لاگ اجرای اتوماسیون',
                'verbose_name_plural': '۲۱. لاگ\u200cهای مانیتورینگ اتوماسیون کارگاه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(max_length=150, verbose_name='نام منبع')),
                ('resource_type', models.CharField(choices=[('machine', 'ماشین\u200cآلات و دستگاه\u200cهای چاپ فیزیکی'), ('designer', 'پرسنل و طراحان ناظر آتلیه'), ('operator', 'اپراتور و کادر کارگاه فنی'), ('cutter', 'میز و دستگاه\u200cهای برش\u200cکاری'), ('laminator', 'دستگاه\u200cهای روکش و سلفون\u200cکشی'), ('vehicle', 'خودروهای ارسال و ناوگان حمل و نقل'), ('shift', 'شیفت\u200cهای کاری و سالن\u200cهای تولید'), ('other', 'سایر منابع متفرقه کارگاه')], max_length=30, verbose_name='نوع منبع')),
                ('capacity_hours', models.PositiveIntegerField(default=8, verbose_name='کل ظرفیت روزانه (ساعت کار)')),
                ('used_hours', models.FloatField(default=0.0, verbose_name='ظرفیت اشغال شده امروز (ساعت)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'منبع کارگاه',
                'verbose_name_plural': '۱۹. مدیریت منابع و ماشین\u200cآلات (Resources)',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_resources',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='orders.resource', verbose_name='منابع کارگاهی تخصیص یافته'),
        ),
    ]
