# Generated by Django 5.2.16 on 2026-07-19 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_automationrule_automationlog_resource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(max_length=150, verbose_name='نام ویزارد')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه ویزارد (Versioning)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizards', to='orders.product', verbose_name='محصول متناظر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'ویزارد پویا',
                'verbose_name_plural': '۲۲. موتور ویزاردهای پویای چاپی (Wizard Engine)',
            },
        ),
        migrations.CreateModel(
            name='WizardConditionalRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('source_field_name', models.CharField(max_length=100, verbose_name='فیلد مبدا شرط')),
                ('value', models.CharField(help_text='مثال: طلاکوب', max_length=100, verbose_name='مقدار شرط')),
                ('target_field_name', models.CharField(blank=True, max_length=100, verbose_name='فیلد هدف اکشن')),
                ('action', models.CharField(choices=[('show', 'نمایش دادن فیلد هدف (Show)'), ('hide', 'مخفی کردن فیلد هدف (Hide)'), ('set_required', 'اجباری کردن فیلد هدف'), ('adjust_price', 'اعمال ضریب افزایش قیمت فاکتور (Price Adjustment)')], default='show', max_length=30, verbose_name='اکشن اتوماتیک')),
                ('price_factor', models.FloatField(default=0.0, help_text='مثلا 0.28 برای افزایش ۲۸ درصدی قیمت کل در صورت برقراری شرط', verbose_name='ضریب تعدیل قیمت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='orders.wizard', verbose_name='ویزارد متناظر')),
            ],
            options={
                'verbose_name': 'قانون منطق شرطی',
                'verbose_name_plural': '۲۳. موتور منطق شرطی و قوانین قیمت\u200cگذاری (Logic Engine)',
            },
        ),
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مرحله')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش مرحله')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='orders.wizard', verbose_name='ویزارد متناظر')),
            ],
            options={
                'verbose_name': 'مرحله ویزارد',
                'verbose_name_plural': 'مراحل ویزاردهای پویا',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='WizardField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(help_text='مثال: lamination_type', max_length=100, verbose_name='شناسه فیلد (انگلیسی)')),
                ('label', models.CharField(help_text='مثال: نوع روکش کارت ویزیت', max_length=150, verbose_name='برچسب فارسی فیلد')),
                ('field_type', models.CharField(choices=[('text', 'فیلد متنی کوتاه (Text)'), ('textarea', 'فیلد متنی عریض (Textarea)'), ('number', 'عدد خام (Number)'), ('select', 'فهرست کشویی انتخابی (Select)'), ('radio', 'دکمه رادیویی تک\u200cانتخابی (Radio)'), ('checkbox', 'چک\u200cباکس چندانتخابی (Checkbox)'), ('file', 'آپلود فایل طراحی (File)'), ('quantity', 'انتخاب تیراژ چاپ (Quantity)')], default='select', max_length=30, verbose_name='نوع فیلد')),
                ('options_json', models.JSONField(blank=True, default=list, help_text="مثال: ['مات', 'براق', 'مخملی']", verbose_name='گزینه\u200cهای فیلد (JSON)')),
                ('is_required', models.BooleanField(default=True, verbose_name='اجباری است؟')),
                ('default_value', models.CharField(blank=True, max_length=150, verbose_name='مقدار پیش\u200cفرض فیلد')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش در مرحله')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='orders.wizardstep', verbose_name='مرحله متناظر')),
            ],
            options={
                'verbose_name': 'فیلد پویا',
                'verbose_name_plural': 'فیلدهای مراحل ویزارد',
                'ordering': ['order_index'],
            },
        ),
    ]
