# Generated by Django 5.2.16 on 2026-07-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_wizard_wizardconditionalrule_wizardstep_wizardfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationlog',
            name='status',
            field=models.CharField(default='executed', max_length=20, verbose_name='وضعیت اجرا'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_payload',
            field=models.TextField(blank=True, verbose_name='متن پیامک یا پارامترها'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_event',
            field=models.CharField(choices=[('order_created', 'ثبت نهایی سفارش جدید (OrderCreated)'), ('payment_completed', 'تسویه حساب موفق فاکتور (PaymentCompleted)'), ('file_uploaded', 'آپلود فایل جدید طرح مشتری (FileUploaded)'), ('qc_failed', 'رد صلاحیت کیفی کار چاپی (QCFailed)')], max_length=50, verbose_name='رویداد راه\u200cانداز'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_percentage',
            field=models.BooleanField(default=True, verbose_name='تخفیف درصدی؟'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'خانه'), ('office', 'شرکت'), ('warehouse', 'انبار')], default='office', max_length=20, verbose_name='نوع آدرس'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان آدرس'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='health_status',
            field=models.CharField(default='healthy', max_length=20, verbose_name='وضعیت سلامت مشتری'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(max_length=30, verbose_name='نوع هزینه'),
        ),
        migrations.AlterField(
            model_name='finish',
            name='factor',
            field=models.FloatField(verbose_name='ضریب قیمت'),
        ),
        migrations.AlterField(
            model_name='finish',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='شناسه یکتا (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='globalconfiguration',
            name='double_side_factor',
            field=models.FloatField(default=1.16, verbose_name='ضریب چاپ دورو رنگی'),
        ),
        migrations.AlterField(
            model_name='globalconfiguration',
            name='free_shipping_threshold',
            field=models.IntegerField(default=3000000, verbose_name='حداقل مبلغ سفارش برای ارسال رایگان (تومان)'),
        ),
        migrations.AlterField(
            model_name='globalconfiguration',
            name='rounding_threshold',
            field=models.IntegerField(default=10000, verbose_name='مبنای رند کردن قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='globalconfiguration',
            name='vat_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد مالیات بر ارزش افزوده (VAT)'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(max_length=100, verbose_name='دسته\u200cبندی نمونه کار'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='آدرس متنی یکتا'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='testimonial_text',
            field=models.TextField(blank=True, verbose_name='متن نقل\u200cقول'),
        ),
        migrations.AlterField(
            model_name='printingsheet',
            name='material',
            field=models.CharField(max_length=100, verbose_name='جنس مشترک فرم'),
        ),
        migrations.AlterField(
            model_name='printingsheet',
            name='max_capacity',
            field=models.PositiveIntegerField(default=80, verbose_name='حداکثر ظرفیت فرم (تعداد کارت)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='شناسه یکتا (انگلیسی)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_production_cost',
            field=models.IntegerField(default=1500, verbose_name='هزینه خام تولید هر واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(default='requested', max_length=20, verbose_name='وضعیت استرداد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='تخصص اصلی'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='department',
            field=models.CharField(default='sales', max_length=20, verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'فوری')], default='medium', max_length=10, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت تیکت'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(default='order', max_length=20, verbose_name='نوع اعلان'),
        ),
        migrations.AlterField(
            model_name='wizard',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='نسخه ویزارد'),
        ),
        migrations.AlterField(
            model_name='wizardconditionalrule',
            name='action',
            field=models.CharField(max_length=30, verbose_name='اکشن اتوماتیک'),
        ),
        migrations.AlterField(
            model_name='wizardconditionalrule',
            name='price_factor',
            field=models.FloatField(default=0.0, verbose_name='ضریب تعدیل قیمت'),
        ),
        migrations.AlterField(
            model_name='wizardconditionalrule',
            name='value',
            field=models.CharField(max_length=100, verbose_name='مقدار شرط'),
        ),
        migrations.AlterField(
            model_name='wizardfield',
            name='field_type',
            field=models.CharField(max_length=30, verbose_name='نوع فیلد'),
        ),
        migrations.AlterField(
            model_name='wizardfield',
            name='label',
            field=models.CharField(max_length=150, verbose_name='برچسب فارسی فیلد'),
        ),
        migrations.AlterField(
            model_name='wizardfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='شناسه فیلد'),
        ),
        migrations.AlterField(
            model_name='wizardfield',
            name='options_json',
            field=models.JSONField(blank=True, default=list, verbose_name='گزینه\u200cهای فیلد'),
        ),
        migrations.AlterField(
            model_name='wizardfield',
            name='order_index',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش'),
        ),
    ]
