# Generated by Django 5.2.16 on 2026-07-20 20:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس متنی (Slug)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کوتاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محتوا',
                'verbose_name_plural': '۱. دسته\u200cبندی\u200cهای محتوایی',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره آموزشی')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='آدرس متنی (Slug)')),
                ('summary', models.TextField(verbose_name='توضیحات کوتاه سرفصل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='مدرس دوره')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'دوره آموزشی',
                'verbose_name_plural': '۷. دوره\u200cهای آموزشی (Academy)',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('question', models.CharField(max_length=255, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ کوتاه کارگاه')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': '۶. سوالات متداول مشتریان (FAQ)',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('file', models.FileField(upload_to='media_library/', verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'تصویر (Image)'), ('pdf', 'کتابچه پی\u200cدی\u200cاف (PDF)'), ('video', 'ویدیو آموزشی (Video)'), ('document', 'سند اداری (Doc/Zip)')], default='image', max_length=20, verbose_name='نوع رسانه')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات استفاده در مقالات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'فایل رسانه\u200cای',
                'verbose_name_plural': '۳. کتابخانه چندرسانه\u200cای (Media Library)',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درس')),
                ('slug', models.SlugField(max_length=255, verbose_name='آدرس متنی (Slug)')),
                ('content', models.TextField(blank=True, verbose_name='محتوای متنی درس')),
                ('order_index', models.PositiveIntegerField(default=1, verbose_name='ترتیب درس')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.course', verbose_name='دوره آموزشی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.mediafile', verbose_name='ویدیو آموزشی')),
            ],
            options={
                'verbose_name': 'درس دوره',
                'verbose_name_plural': 'درس\u200cهای دوره\u200cهای آموزشی',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.mediafile', verbose_name='تصویر کاور'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='آدرس متنی (Slug)')),
                ('content', models.TextField(verbose_name='محتوای HTML/متنی صفحه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('page_type', models.CharField(choices=[('static', 'صفحه ایستای عمومی (Static)'), ('landing', 'صفحه فرود تبلیغاتی (Landing)')], default='static', max_length=20, verbose_name='نوع صفحه')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه صفحه (Versioning)')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'صفحه سیستم',
                'verbose_name_plural': '۵. صفحات ایستا و فرود (CMS)',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='آدرس متنی (Slug)')),
                ('summary', models.TextField(verbose_name='خلاصه مقاله')),
                ('content', models.TextField(verbose_name='متن کامل مقاله')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('review', 'در انتظار بازبینی'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=20, verbose_name='وضعیت انتشار')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار (ساعت\u200cبندی)')),
                ('reading_time', models.PositiveIntegerField(default=5, verbose_name='زمان مطالعه (دقیقه)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید کل')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='content.category', verbose_name='دسته\u200cبندی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.mediafile', verbose_name='تصویر شاخص')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'مقاله وبلاگ',
                'verbose_name_plural': '۴. مقالات وبلاگ چاپی',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.post', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات و دیدگاه\u200cهای کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(max_length=100, verbose_name='نام برچسب')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس متنی (Slug)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'برچسب محتوا',
                'verbose_name_plural': '۲. برچسب\u200cهای وبلاگ',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='content.tag', verbose_name='برچسب\u200cها'),
        ),
    ]
