# Generated by Django 5.2.16 on 2026-07-19 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_alter_automationlog_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('name', models.CharField(help_text='مثال: zarinpal', max_length=50, unique=True, verbose_name='شناسه درگاه (انگلیسی)')),
                ('title', models.CharField(help_text='مثال: زرین\u200cپال', max_length=100, verbose_name='عنوان فارسی درگاه')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات فنی (API Keys / Credentials)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': '۱. درگاه\u200cهای پرداخت',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('subtotal', models.IntegerField(verbose_name='مبلغ خام سفارش (تومان)')),
                ('tax', models.IntegerField(default=0, verbose_name='مالیات بر ارزش افزوده (تومان)')),
                ('discount', models.IntegerField(default=0, verbose_name='مبلغ تخفیف (تومان)')),
                ('shipping', models.IntegerField(default=0, verbose_name='هزینه حمل و نقل (تومان)')),
                ('grand_total', models.IntegerField(verbose_name='مبلغ نهایی فاکتور (تومان)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس فاکتور'), ('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده و موفق'), ('cancelled', 'لغو شده'), ('refunded', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت فاکتور')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور فاکتور')),
                ('due_date', models.DateTimeField(verbose_name='مهلت پرداخت فاکتور')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order', verbose_name='سفارش متناظر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'فاکتور رسمی',
                'verbose_name_plural': '۲. فاکتورهای رسمی',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('amount', models.IntegerField(verbose_name='مبلغ تراکنش (تومان)')),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین از درگاه'), ('bank_transfer', 'فیش واریزی / کارت\u200cبه\u200cکارت'), ('cash', 'نقدی کارگاه'), ('manual', 'تسویه حساب دستی')], default='online', max_length=30, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('waiting', 'معلق در درگاه'), ('authorized', 'تایید شده اولیه'), ('paid', 'پرداخت موفق و تسویه شده'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده'), ('refunded', 'کل مبلغ مرجوع شد'), ('partially_refunded', 'مبلغی از تراکنش مرجوع شد')], default='pending', max_length=30, verbose_name='وضعیت تراکنش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.invoice', verbose_name='فاکتور متناظر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': '۳. تراکنش\u200cهای پرداخت سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('authority', models.CharField(max_length=150, unique=True, verbose_name='شناسه توکن درگاه (Authority)')),
                ('amount', models.IntegerField(verbose_name='مبلغ تراکنش به تومان')),
                ('status', models.CharField(choices=[('pending', 'ایجاد شده در درگاه'), ('paid', 'پرداخت موفق بانک'), ('failed', 'ناموفق / لغو شده')], default='pending', max_length=20, verbose_name='وضعیت تراکنش')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری بانک (RefID)')),
                ('response_log', models.JSONField(blank=True, default=dict, verbose_name='پاسخ کامل وب\u200cسرویس درگاه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payments.gateway', verbose_name='درگاه پرداخت')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.payment', verbose_name='پرداخت مربوطه')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'تلاش پرداخت درگاه',
                'verbose_name_plural': '۴. تلاش\u200cهای پرداخت بانک',
            },
        ),
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('amount', models.IntegerField(verbose_name='مبلغ تراکنش')),
                ('ref_id', models.CharField(max_length=100, verbose_name='شماره پیگیری تراکنش')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='وضعیت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentattempt', verbose_name='تلاش پرداخت')),
            ],
            options={
                'verbose_name': 'لاگ تراکنش درگاه',
                'verbose_name_plural': '۵. آرشیو تراکنش\u200cهای مستقیم درگاه',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('action', models.CharField(max_length=100, verbose_name='رویداد تراکنش (Action)')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات و پارامترها')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('browser_agent', models.CharField(max_length=255, verbose_name='مرورگر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='payments.payment', verbose_name='پرداخت')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ مانیتورینگ مالی',
                'verbose_name_plural': '۷. لاگ\u200cهای اودیت پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='شناسه عددی')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتای UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='زمان حذف نرم')),
                ('amount', models.IntegerField(verbose_name='مبلغ استرداد (تومان)')),
                ('reason', models.TextField(verbose_name='علت مرجوعی')),
                ('status', models.CharField(choices=[('requested', 'درخواست شده (معلق)'), ('approved', 'تایید شده (در انتظار پرداخت)'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده و تسویه موفق')], default='requested', max_length=20, verbose_name='وضعیت ممیزی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='سرپرست ممیزی مالی')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='تراکنش اصلی پرداخت')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'درخواست مرجوعی',
                'verbose_name_plural': '۶. درخواست\u200cهای استرداد وجه (Refunds)',
            },
        ),
    ]
